package core

import (
	go_fuzz_utils "github.com/trailofbits/go-fuzz-utils"
)

func GetTypeProvider(data []byte) (*go_fuzz_utils.TypeProvider, error) {
	tp, err := go_fuzz_utils.NewTypeProvider(data)
	if err != nil {
		return nil, err
	}
	err = tp.SetParamsStringBounds(0, 1024)
	if err != nil {
		return nil, err
	}
	err = tp.SetParamsSliceBounds(0, 4096)
	if err != nil {
		return nil, err
	}
	err = tp.SetParamsBiases(0, 0, 0, 0)
	if err != nil {
		return nil, err
	}
	return tp, nil
}

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processBlockHeader__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processExecutionPayload__ because parameters include func, chan, or unsupported interface: ContextT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_ProcessBlock__ because parameters include func, chan, or unsupported interface: ContextT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_Transition__ because parameters include func, chan, or unsupported interface: ContextT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processRandaoReveal__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processOperations__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_validateExecutionPayload__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_validateStatefulPayload__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_validateStatelessPayload__ because parameters include func, chan, or unsupported interface: BeaconBlockT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_InitializePreminedBeaconStateFromEth1__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processWithdrawals__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_createValidator__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_addValidatorToRegistry__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_applyDeposit__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processDeposit__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processDeposits__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processSlash__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processSyncCommitteeUpdates__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_ProcessSlots__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_getAttestationDeltas__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processEpoch__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processProposerSlashing__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processRandaoMixesReset__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processRewardsAndPenalties__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processSlashings__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processSlashingsReset__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_processSlot__ because parameters include func, chan, or unsupported interface: BeaconStateT

// skipping Fuzz_Nosy_StateProcessor[BeaconBlockT BeaconBlock[DepositT, BeaconBlockBodyT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], BeaconBlockHeaderT BeaconBlockHeader[BeaconBlockHeaderT], BeaconStateT BeaconState[BeaconStateT, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT], ContextT Context, DepositT Deposit[ForkDataT, WithdrawalCredentialsT], Eth1DataT interface{GetDepositCount() math.U64; New(common.Root, math.U64, common.ExecutionHash) Eth1DataT}, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, ForkT interface{New(common.Version, common.Version, math.Epoch) ForkT}, ForkDataT ForkData[ForkDataT], KVStoreT any, ValidatorT Validator[ValidatorT, WithdrawalCredentialsT], ValidatorsT interface{HashTreeRoot() common.Root; ~[]ValidatorT}, WithdrawalT Withdrawal[WithdrawalT], WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int; ~[]WithdrawalT}, WithdrawalCredentialsT ~[32]byte]_buildRandaoMix__ as it appears to be an interface:

// skipping Fuzz_Nosy_BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetBlobKzgCommitments__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetDeposits__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetExecutionPayload__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetRandaoReveal__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_HashTreeRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT any, ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_GetBodyRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_GetParentBlockRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_GetProposerIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_GetSlot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_GetStateRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_HashTreeRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_New__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlockHeader[BeaconBlockHeaderT any]_SetStateRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockHeader[BeaconBlockHeaderT any]

// skipping Fuzz_Nosy_BeaconBlock[DepositT any, BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetBody__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlock[DepositT any, BeaconBlockBodyT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlock[DepositT any, BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetParentBlockRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlock[DepositT any, BeaconBlockBodyT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlock[DepositT any, BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetProposerIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlock[DepositT any, BeaconBlockBodyT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlock[DepositT any, BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetSlot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlock[DepositT any, BeaconBlockBodyT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlock[DepositT any, BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_GetStateRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlock[DepositT any, BeaconBlockBodyT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconBlock[DepositT any, BeaconBlockBodyT BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT ExecutionPayloadHeader, WithdrawalsT any]_IsNil__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlock[DepositT any, BeaconBlockBodyT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconBlockBody[BeaconBlockBodyT, DepositT, ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader, WithdrawalsT any]

// skipping Fuzz_Nosy_BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]_Context__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]_Copy__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]_HashTreeRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]_NewFromDB__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.BeaconState[T, BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, KVStoreT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_Context_GetOptimisticEngine__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Context

// skipping Fuzz_Nosy_Context_GetSkipPayloadVerification__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Context

// skipping Fuzz_Nosy_Context_GetSkipValidateRandao__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Context

// skipping Fuzz_Nosy_Context_GetSkipValidateResult__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Context

// skipping Fuzz_Nosy_Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]_GetAmount__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]_GetPubkey__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]_GetWithdrawalCredentials__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]_VerifySignature__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Deposit[ForkDataT any, WithdrawlCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_ExecutionEngine[ExecutionPayloadT ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT any, WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int}]_VerifyAndNotifyNewPayload__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionEngine[ExecutionPayloadT github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT], ExecutionPayloadHeaderT any, WithdrawalsT interface{EncodeIndex(int, *bytes.Buffer); Len() int}]

// skipping Fuzz_Nosy_ExecutionPayloadHeader_GetBlockHash__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayloadHeader

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetBaseFeePerGas__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetBlobGasUsed__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetBlockHash__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetExcessBlobGas__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetExtraData__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetFeeRecipient__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetGasLimit__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetGasUsed__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetLogsBloom__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetNumber__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetParentHash__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetPrevRandao__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetReceiptsRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetStateRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetTimestamp__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetTransactions__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_GetWithdrawals__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]_ToHeader__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ExecutionPayload[ExecutionPayloadT, ExecutionPayloadHeaderT, WithdrawalsT any]

// skipping Fuzz_Nosy_ForkData[ForkDataT any]_ComputeRandaoSigningRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ForkData[ForkDataT any]

// skipping Fuzz_Nosy_ForkData[ForkDataT any]_New__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ForkData[ForkDataT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetBalance__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetBlockRootAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetFork__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetGenesisValidatorsRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetLatestBlockHeader__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetNextWithdrawalIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetNextWithdrawalValidatorIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetSlashingAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetSlot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetTotalActiveBalances__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetTotalSlashing__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetTotalValidators__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetValidators__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_GetValidatorsByEffectiveBalance__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]_ValidatorIndexByCometBFTAddress__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT, ValidatorsT, WithdrawalT any]

// skipping Fuzz_Nosy_ReadOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]_GetEth1Data__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]

// skipping Fuzz_Nosy_ReadOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]_GetEth1DepositIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]

// skipping Fuzz_Nosy_ReadOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]_GetLatestExecutionPayloadHeader__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]

// skipping Fuzz_Nosy_ReadOnlyRandaoMixes_GetRandaoMixAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyRandaoMixes

// skipping Fuzz_Nosy_ReadOnlyStateRoots_StateRootAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyStateRoots

// skipping Fuzz_Nosy_ReadOnlyValidators[ValidatorT any]_ValidatorByIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyValidators[ValidatorT any]

// skipping Fuzz_Nosy_ReadOnlyValidators[ValidatorT any]_ValidatorIndexByPubkey__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyValidators[ValidatorT any]

// skipping Fuzz_Nosy_ReadOnlyWithdrawals[WithdrawalT any]_ExpectedWithdrawals__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.ReadOnlyWithdrawals[WithdrawalT any]

// skipping Fuzz_Nosy_Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]_GetEffectiveBalance__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]_GetPubkey__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]_GetWithdrawableEpoch__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]_IsSlashed__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]_New__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]_SetEffectiveBalance__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]_SizeSSZ__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validator[ValidatorT any, WithdrawalCredentialsT ~[32]byte]

// skipping Fuzz_Nosy_Validators_HashTreeRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Validators

// skipping Fuzz_Nosy_Withdrawal[WithdrawalT any]_Equals__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Withdrawal[WithdrawalT any]

// skipping Fuzz_Nosy_Withdrawal[WithdrawalT any]_GetAddress__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Withdrawal[WithdrawalT any]

// skipping Fuzz_Nosy_Withdrawal[WithdrawalT any]_GetAmount__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Withdrawal[WithdrawalT any]

// skipping Fuzz_Nosy_Withdrawal[WithdrawalT any]_GetIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Withdrawal[WithdrawalT any]

// skipping Fuzz_Nosy_Withdrawal[WithdrawalT any]_GetValidatorIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.Withdrawal[WithdrawalT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_DecreaseBalance__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_IncreaseBalance__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_SetFork__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_SetGenesisValidatorsRoot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_SetLatestBlockHeader__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_SetNextWithdrawalIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_SetNextWithdrawalValidatorIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_SetSlot__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_SetTotalSlashing__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_UpdateBlockRootAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]_UpdateSlashingAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyBeaconState[BeaconBlockHeaderT, Eth1DataT, ExecutionPayloadHeaderT, ForkT, ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]_SetEth1Data__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]

// skipping Fuzz_Nosy_WriteOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]_SetEth1DepositIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]

// skipping Fuzz_Nosy_WriteOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]_SetLatestExecutionPayloadHeader__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyEth1Data[Eth1DataT, ExecutionPayloadHeaderT any]

// skipping Fuzz_Nosy_WriteOnlyRandaoMixes_UpdateRandaoMixAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyRandaoMixes

// skipping Fuzz_Nosy_WriteOnlyStateRoots_UpdateStateRootAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyStateRoots

// skipping Fuzz_Nosy_WriteOnlyValidators[ValidatorT any]_AddValidator__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyValidators[ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyValidators[ValidatorT any]_AddValidatorBartio__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyValidators[ValidatorT any]

// skipping Fuzz_Nosy_WriteOnlyValidators[ValidatorT any]_UpdateValidatorAtIndex__ because parameters include func, chan, or unsupported interface: github.com/berachain/beacon-kit/mod/state-transition/pkg/core.WriteOnlyValidators[ValidatorT any]
